export const QUERY_KEYS = {
  mileageList: 'mileageList',
  submittedMileage: 'submittedMileage',
  isAppliedScholarship: 'isAppliedScholarship',
  scholarshipDuration: 'scholarshipDuration',
  etcMileageList: 'etcMileageList',
  userInfo: 'userInfo',
  capability: 'capability',
  compareCapability: 'compareCapability',
  semesterCapability: 'semesterCapability',
  award: 'award',
  project: 'project',
  topProject: 'topProject',
  profile: 'profile',
  profileImage: 'profileImage',
  profileShare: 'profileShare',
  techStack: 'techStack',
  techStackShare: 'techStackShare',
  mileageCountShare: 'mileageCountShare',
  awardCountShare: 'awardCountShare',
};
