export const ROUTE_PATH = {
  login: '/',
  dashboard: '/dashboard',
  mileageList: '/mileage',
  newMileage: '/mileage/add',
  archive: '/archive',
  award: '/archive/award',
  project: '/archive/project',
  projectDetail: (projectId: number) => `/archive/project/${projectId}`,
  newProject: '/archive/project/add',
  editProject: (projectId: string) => `/archive/project/${projectId}/edit`,
  scholarship: '/scholarship/apply',
  profile: '/profile',
  profileShare: (id: string) => `/profile/${id}`,
};
