export const ROUTE_PATH = {
  login: '/',
  dashboard: '/dashboard',
  mileageList: '/mileage',
  newMileage: '/mileage/add',
  archive: '/archive',
  award: '/archive/award',
  project: '/archive/project',
  projectDetail: (id: number) => `/archive/project/${id}`,
  newProject: '/archive/project/add',
  editProject: '/archive/project/edit',
  scholarship: '/scholarship/apply',
  profile: '/profile',
  profileShare: (id: number) => `profile/${id}`,
};
